name: Psalm Static Analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          composer_require_dev: true
          security_analysis: true
